docs/api/index.html, pkg/ivd/ivd_protected_entity_type_manager.go
Resolved the NotAuthenticated error due to lack of the KeepAlive mechanism in govmomi connection.
=> Resolved the NotAuthenticated error 

.github/workflows/ci.yml
Added the basic CI framework for astrolabe using Github Action. We can further refine it later.
=> Added github action CI

.github/workflows/ci.yml, Makefile
Resolved a dependency issue w.r.t to a recent change. Meanwhile, added the nightly build for the astrolabe repo to notify any other incoming dependency issues.
=> Resolved a dependency issue w.r.t to a recent change

pkg/s3repository/repository_protected_entity_type_manager.go
=> Added creation log for S3 repo that logs bucket and prefix

go.sum, pkg/ivd/ivd_protected_entity_type_manager_test.go, pkg/ivd/ivd_protected_entity_type_manager_util.go
Fix to provide more robust logic to find shared datastores for node VMs in multi DCs environment
=> Fix to provide more robust logic to find shared datastores for node VMs in multi DCs environment

vendor/github.com/vmware/gvddk/README.md
=> Updated readme for 7.0.0 dependency

pkg/ivd/ivd_protected_entity_test.go
Added a test case to backup encrypted IVDs. In the vSphere 7.0, NBDSSL works fine while NBD does not. 
Testing:
`ASTROLABE_VC_URL='https://<vcUser>:<vcPassword>@<vcIP>:<port>/sdk' go test -run TestBackupEncryptedIVD -v`
=> Added a test case to backup encrypted IVDs

pkg/s3repository/repository_protected_entity.go, pkg/s3repository/repository_protected_entity_type_manager.go
1. Astrolabe changes for cancelling ongoing uploads.
=> Cancel ongoing upload

changelogs/unreleased/0026-dsmithuchida, pkg/astrolabe/protected_entity.go, pkg/fs/fs_protected_entity.go, pkg/ivd/ivd_protected_entity.go, pkg/kubernetes/kubernetes_namespace_protected_entity.go, pkg/s3repository/repository_protected_entity.go
=> Change GetMetadataReader to return a ReadCloser rather than a Reader

pkg/astrolabe/constants.go, pkg/astrolabe/protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go
Signed-off-by: Swati Gupta <swgupta@swgupta-a01.vmware.com>
=> Add func to get PE ID given the kubernetes object kind, name and namespace

pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/pvc/utils.go
This PR adds CreateFromMetadata for PVC PETM.
Signed-off-by: xing-yang <xingyang105@gmail.com>
=> WIP: Add CreateFromMetadata for PVC PETM

pkg/pvc/pvc_protected_entity_type_manager.go
This PR clears out some fields before creating a new PVC.
=> Clear out some fields before creating new PVC

changelogs/unreleased/0038-dsmithuchida, pkg/astrolabe/protected_entity.go, pkg/client/client_protected_entity.go, pkg/client/client_protected_entity_type_manager.go, pkg/fs/fs_protected_entity.go, pkg/fs/fs_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_test.go, pkg/ivd/ivd_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity_type_manager_test.go, pkg/kubernetes/kubernetes_namespace_protected_entity.go, pkg/kubernetes/kubernetes_namespace_protected_entity_type_manager.go, pkg/pvc/pvc_protected_entity.go, pkg/s3repository/repository_protected_entity.go
Implemented Overwrite for IVD
Minor cleanup in IVD tests
Builds on top of clone-params PR, let's review/merge that first before reviewing this one.
=> Added Overwrite API to Protected Entity

pkg/s3repository/repository_protected_entity_type_manager.go
Signed-off-by: xing-yang <xingyang105@gmail.com>
=> Add missing params to Copy method in S3Repository PETM

cmd/astrolabe/main.go, pkg/astrolabe/protected_entity.go, pkg/client/client_protected_entity.go, pkg/fs/fs_protected_entity.go, pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_test.go, pkg/kubernetes/kubernetes_namespace_protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/s3repository/repository_protected_entity.go, pkg/s3repository/repository_protected_entity_type_manager.go, pkg/server/service_api.go
1. Require params to deliver the backup repository.
2. No funtional change yet, only API defn changed.
Testing:
build.
=> Add params to DeleteSnapshot API

pkg/astrolabe/protected_entity.go, pkg/ivd/ivd_protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go
1. Changed encoding.
2. Updated logging.
3. DeleteSnapshot in pvc pe update.
Signed-off-by: Deepak Kinni dkinni@vmware.com
=> DeleteSnapshot astrolabe changes

pkg/ivd/ivd_protected_entity_type_manager_util.go
Fixed the known issue that fail to recursively retrieve datastores within datacenter inventory in the restore path. With the fix, the following issues can be resolved.
- Failed to restore if there is no datastores under the top level of datacenter inventory. (https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/161#issuecomment-679854095)
- Failed to restore if datacenter inventories are place under non-root folders. (https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/161#issuecomment-680695497)
Testing:
- Local integration test: `KUBECONFIG=<path to a kubeconfig file> go test ./pkg/ivd/... -run TestRestoreCnsVolumeFromSnapshot  -v`
=> Enabled the recursive retrieval of datastores within datacenter inventory

pkg/pvc/pvc_protected_entity_type_manager.go
This change is needed for restore.
=> Add backupRepositoryName to CreateFromMetadata

pkg/pvc/pvc_protected_entity_type_manager.go
1. This br name is further passed into download CR.
=> Include BackupRepositoryName as part of CloneParams

pkg/common/vsphere/cns_manager.go, pkg/common/vsphere/vslm_manager.go, pkg/ivd/ivd_protected_entity.go
=> Break on success of API invocation

changelogs/unreleased/0052-carlbraganza, changelogs/unreleased/052-carlbraganza, vendor/github.com/vmware/gvddk/README.md, vendor/github.com/vmware/gvddk/gDiskLib/gvddk_api.go, vendor/github.com/vmware/gvddk/gDiskLib/gvddk_c.c, vendor/github.com/vmware/gvddk/gDiskLib/gvddk_c.h, vendor/github.com/vmware/gvddk/gDiskLib/gvddk_helper.go, vendor/github.com/vmware/gvddk/gvddk-high/gvddk.go, vendor/github.com/vmware/gvddk/test/Multithread_test.go, vendor/github.com/vmware/gvddk/test/Open_test.go, vendor/github.com/vmware/gvddk/test/low_level_test.go
Made the GVDDK unit tests work for VDDK 7.0 and support test invocation from under bash.
=> Added GVDDK support for the QueryAllocatedBlocks function.

pkg/common/vsphere/vcenter_utils.go, pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity_type_manager_util.go
1. Improve logging
2. log the time taken and retry count for DeleteSnapshot.
3. Change from Info to Debug for few log statements.
Cherry-pick: https://github.com/vmware-tanzu/astrolabe/pull/65
=> [Cherry-pick]Update Logging (#65)

pkg/util/utils.go
During the installation of csi driver users have an option to use a non-default file name to enter vCenter config.
A secret(vsphere-config-secret) is created from the file, the 'Data' of the secret consists of key-value pairs, the key being the file name of the vCenter config.
Currently, we explicitly look for the default key(csi-vsphere.conf) in the Secret, however, if users created a non-default file name for the vc config then our plugin would fail to read the vc config.
The current change directly reads the value, since the Secret is expected to contain only 1 kv pair(confirmed this with csi team) and the file name used to create the secret is of no concern to the plugin.
Testing:
In-Progress
=> Allow reading non default secrets

changelogs/unreleased/0075-dsmithuchida, gen/models/protected_entity_info.go, openapi/astrolabe_api.yaml, pkg/astrolabe/protected_entity_info.go, pkg/fs/fs_data_source_test.go, pkg/fs/fs_protected_entity.go, pkg/fs/fs_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/s3repository/repository_protected_entity_type_manager.go
=> Added size field/attribute for Protected Entities

changelogs/unreleased/0077-dsmithuchida, cmd/astrolabe/main.go, pkg/astrolabe/pe_zip.go, pkg/astrolabe/pe_zip_test.go
This allows a protected entity inside a Zip file to be accessed.
=> Added ZipProtectedEntity (pkg/astrolabe/pe_zip.go)

cmd/astrolabe/main.go, pkg/astrolabe/pe_zip.go, pkg/astrolabe/pe_zip_test.go
The following change are included.
1. Updated the cp command in astrolabe cli to support copying from zip file to a protected entity
2. Updated the implementation of the command, cp, by moving away the detail about zip PE.
Testing:
Below is the config directory. The path of config directory is of your choice.
```
$tree ~/astrolabe/
/home/lintongj/astrolabe/
├── pes
│   └── ivd.pe.json
└── s3config.json
```
1. Copy from PE snapshot to zip file. Below is an example command.
```
astrolabe --confDir ~/astrolabe cp ivd:5d69f3df-2709-4472-9c13-919770f87ea5:2a2b2ff9-e0ee-4a21-a0a0-654f2f4789ad /tmp/destfile10mi.zip
```
2. Overwrite from zip file to an existing PE. Below is an example command.
```
./cmd/astrolabe/astrolabe --confDir ~/astrolabe overwrite /tmp/destfile10mi.zip …
```
=> Updated the cp command in astrolabe cli and added the overwrite command to support overwriting an existing PE with a zip file

pkg/server/server_core.go
=> Added the changes to returning err

docs/SPEC.md
Corrected due to my OCD on this one :D
=> Lowercase w for VMware

pkg/astrolabe/protected_entity_type_manager.go
=> Added methods to convert CopyCreateOptions to/from strings

.github/workflows/ci.yml, go.mod
=> Updated CI workflow to use go 1.16

MAINTAINERS.md
=> Added Rafael Brito as a maintainer

pkg/s3repository/repository_protected_entity_manager.go
Handles multiple PE types in an S3 bucket
=> Implemented S3 RepositoryProtectedEntityManager

Makefile, pkg/localsnap/localsnap_repo.go
Fixed a compile error introduced
=> Added localsnap to Makefile, fixed bug in localsnap_repo.go

Makefile, pkg/localsnap/localsnap_repo.go
This is a cherry pick PR for #102
=> [Cherry-pick] Added localsnap repository

go.mod, go.sum
This is a cherry pick pr for #127
=> [Cherry-pick] Update gogo protobuf version to 1.3.2

pkg/s3repository/repository_protected_entity_manager.go
This is a cherry pick for PR #103
=> [Cherry-pick] Implemented S3 RepositoryProtectedEntityManager - handles multiple PE

Makefile, pkg/localsnap/localsnap_repo.go
This is a cherry pick pr for #124
=> [Cherry-pick] Added localsnap to Makefile, fixed bug in localsnap_repo.go
