vmware-tanzu/astrolabe

Makefile
The most recent commit of googleapis/gnostic on Jan 31, 2020 (https://github.com/googleapis/gnostic/commit/896953e6749863beec38e27029c804e88c3144b8), which rename some dirs from uppercase to lowercase, introduced some dependency issue. To make sure the build work properly, checking out the v0.4.0 tag of this project as a workaround.
=> use googleapis/gnostic v0.4.0 to workaround a dependency issue

go.mod, go.sum, pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_test.go
Added retries in CreateSnapshot/DeleteSnaption Implementation to workaround the known issue of race condition from the platfrom APIs. Below are changes included in this commit.
1. Change in go.mod to pick up the recent fix in govmomi to throw expected type of error from VSLM task. Please refer to https://github.com/vmware/govmomi/pull/1888 for the detail.
2. Change of retries made in CreateSnapshot/DeleteSnapshot implementation in pkg/ivd/ivd_protected_entity.go.
3. Added a new test case in pkg/ivd/ivd_protected_entity_test.go to reproduce the issue of known race condition and to verify the correctness of this fix. With this fix, the test case is consistently passed.
=> Added Retries in CreateSnapshot/DeleteSnaption Implementation

pkg/ivd/ivd_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity_type_manager_test.go, pkg/ivd/ivd_protected_entity_type_manager_util.go
Fix to find all shared datastores rather than all datastores for PV provisioning in the restore code path. There are a few defects for this fix.
1. The restore of storage policy is not fully supported.
2. Ruled out certain NFS datastores.
3. The process of finding eligible datastores could still be time consuming.
It should be OK for the first release though.
=> Fix to find all shared datastores for PV provisioning in Restore

pkg/ivd/ivd_protected_entity_type_manager_util.go
Currently not working with vm in folder. Fix to use "..." to find vms recursively.
Reference to https://godoc.org/github.com/vmware/govmomi/find.
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
=> Fix datacenter vm path to work if vms in folder

Makefile, go.mod, go.sum, pkg/astrolabe/protected_entity.go, pkg/ivd/ivd_protected_entity_type_manager_test.go, pkg/ivd/ivd_protected_entity_type_manager_util.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/server/direct_protected_entity_manager.go, pkg/util/utils.go
Added a new PE type for PVC
Testing:
- Functional Test:
- - `KUBECONFIG=~/.kube/config go test -run TestGetPVCComponents -timeout 0 -v` - PASS
- - `KUBECONFIG=~/.kube/config go test -run TestSnapshotOps -timeout 0 -v` - PASS
- Regression Test:
- - https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/215/  (On-going)
=> Added a new PE type for PVC

pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/server/direct_protected_entity_manager.go
1. Added the support to register external PETM
2. Adapted to select the right component PE between IVD and Paravirt from PVC PE
=> Added the support to register external PETM

pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_test.go
Improved the retry workaround in IVD Snapshot API implemention regarding the race between concurrent snapshot/deleteSnapshot API invocations
Testing:
Run IVD PE test case, TestSnapshotOpsUnderRaceCondition, for 100 times.
`NUM_OF_IVD=12 ASTROLABE_VC_URL='https://<vsphere user>:<vsphere password>@<vc ip>/sdk' go test ./pkg/ivd/... -run TestSnapshotOpsUnderRaceCondition -timeout 0 -v -failfast -count 100`
=> Improved the retry workaround in IVD Snapshot API implemention

cmd/astrolabe_server/main.go, pkg/client/client_protected_entity_manager.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/s3repository/repository_protected_entity_type_manager_test.go, pkg/server/openapi_handlers.go, pkg/server/task_manager.go
Changed to use TaskManager and ClientProtectedEntityManager to use pointer in methods,
fixes copying of mutex
Fixed error message in astrolabe_server to actually output when apiPort not an integer
Fixed S3 repo test to use newer APIs, now compiles
Fixed params in pvc_protected_entity_type_manager_test, now compiles
=> Changes to pass go vet

pkg/ivd/ivd_protected_entity.go, pkg/util/utils.go, pkg/util/utils_test.go
A simple change to update DeleteSnapshot and CreateSnapshot APIs to retry on "connection reset by peer" network issue. Add unit test to check string comparison.
Precheck: https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/524/
Relevant bug link:
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2614753
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2634621
=> Catch connection reset by peer network issue in DeleteSnapshot and CreateSnapshot

cmd/astrolabe/main.go, gen/restapi/server.go, pkg/kubernetes/kubernetes_namespace_protected_entity_type_manager.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/utils.go
Calls from the CLI will not have a context for cancellation
Removed context.TODO(), added context to function arguments where needed
=> Changed from context.TODO to context.Background in CLI.

pkg/common/vsphere/cns_manager.go, pkg/common/vsphere/vslm_manager.go, pkg/ivd/ivd_protected_entity.go
1. The errors are inspected in the upper layer to determine if it needs to be retried.
2. Wrapping the error loses the error type.
3. Prevent retry on RetrieveSanpshotDetails failure on non IvalidArg faults.
4. Additional logging.
=> Pass api error to IVD PE

.github/workflows/ci.yml
Fixed github action script due to deprecated command, set-env
=> Fixed github action script due to deprecated command, set-env

pkg/astrolabe/constants.go, pkg/ivd/ivd_protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go
1. If Pandora does not find the FCD in its in-memory cache delete snapshot immediately returns a NotFound error. The current change checks if a NotFound error is returned, if so it assumes the DeleteSnapshot as a success.
2. Triggering GetComponents on a PVC PE queries the k8s API server for the pvc, this causes an issue when we are deleting backup on a fresh setup connected to a bucket that contains older backups. The change removes any call to k8s API server in the DeleteSnapshot Path.
3. Removed called to GetPVC in pvc petm as it's not used, code paths that require PVC info call the GetPVC method explicitly.
=> DeleteSnapshot fixes

.github/workflows/ci.yml
Fixed github action script due to deprecated command, set-env
Cherry-pick https://github.com/vmware-tanzu/astrolabe/pull/64
=> [Cherry-pick] Fixed github action script due to deprecated command, set-env (#64)

pkg/astrolabe/constants.go, pkg/ivd/ivd_protected_entity.go, pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go
1. If Pandora does not find the FCD in its in-memory cache delete snapshot immediately returns a NotFound error. The current change checks if a NotFound error is returned, if so it assumes the DeleteSnapshot as a success.
2. Triggering GetComponents on a PVC PE queries the k8s API server for the pvc, this causes an issue when we are deleting backup on a fresh setup connected to a bucket that contains older backups. The change removes any call to k8s API server in the DeleteSnapshot Path.
3. Removed called to GetPVC in pvc petm as it's not used, code paths that require PVC info call the GetPVC method explicitly.
Cherry-pick: https://github.com/vmware-tanzu/astrolabe/pull/62
=> [Cherry-pick]DeleteSnapshot fixes (#62)

changelogs/unreleased/0076-dkinni, pkg/ivd/ivd_protected_entity.go, pkg/ivd/ivd_protected_entity_type_manager.go
During the data-manager and backupdriver startup, an attempt is made to initialize ivd petm.
Before the fix, the ivd petm would not be registered if there were errors while establishing a vCenter connection.
Even if the vc comes back online, there was no mechanism to re-register ivd petm.
With this fix, the ivd petm is registered even if there were errors while initializing ivd petm.
Furthermore, the vcenter connections are checked before any vCenter operation, and connections are re-established if no present.
Confluence:
https://confluence.eng.vmware.com/display/~dkinni/Disconnected+VC+Connection+Reconciliation+Velero+vSphere+Plugin
Testing
Please refer https://confluence.eng.vmware.com/display/~dkinni/Disconnected+VC+Connection+Reconciliation+Velero+vSphere+Plugin for all the testing …
=> Disconnected vCenter reconciliation

.github/workflows/ci.yml
Change VDDK libs from 7.0 to 7.0.2
Tested with basic backup/restore operation.
Precheck test passed: https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/1055/
=> Change to use 7.0.2 vddk libs from 7.0

go.mod, go.sum, pkg/ivd/ivd_protected_entity_type_manager.go, pkg/util/utils.go
Currently we hardcoding the default log level by explicitly calling VixDiskLib_Init in VDDK side. 
VDDK has a function VixDiskLib_InitEx which allows user to pass a config file which contains customized log level configuration. We have already added the gvddk wrapper function for VixDiskLib_InitEx, we need to update our vsphere plugin to allow user to configure log level during run time.
This change includes:
1. Pick up virtual-disks change.
2. Change to use disklib.InitEx and pass a config file path when initializing vddk lib.
Manually tested. Detail test steps refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/354.
=> Make vddk log level configurable

pkg/common/vsphere/virtual_center.go
In 7.0u3 WCP setups the insecure flag is set to false by default, to support this fully we would need astrolabe to set the right certificate and thumbprint while creating vc clients. Since the required certificates are not available to the plugin yet, we would continue to use insecure connection by overriding the config value.
Testing Done:
Ensured vc connections were successfully created when the insecure-flag=true.
Verified that password rotation recreates new connection.
=> Always use insecure connections for vc client

cmd/astrolabe/main.go, cmd/astrolabe_server/main.go, pkg/fs/fs_protected_entity_type_manager.go, pkg/ivd/ivd_protected_entity_type_manager.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/tests/pvc_protected_entity_type_manager_test.go, pkg/server/astrolabe.go, pkg/server/direct_protected_entity_manager.go
Allows for external PE types to be loaded into the ProtectedEntityManager.
=> Added addonInits to ProtectedEntityManager

cmd/astrolabe_server/main.go, pkg/server/server_core.go
Moved server functionality into pkg/server/server_core.go to allow for different callers with different plugin sets
=> Moved server functionality into pkg/server/server_core.go to allow for different callers with different plugin sets

pkg/astrolabe/protected_entity_info.go
FillFromModel was using wrong array to iterate over (componentIDs instead of jsonStruct.ComponentSpecs)
=> Fixed bug in FillFromModel

pkg/s3repository/repository_protected_entity_type_manager.go
GetProtectedEntitiesByIDPrefix was using the wrong token for continuation and was not paginating correctly
=> Fixed bug in S3 GetProtectedEntitiesByIDPrefix

pkg/astrolabe/protected_entity.go
Strips snapshot ID from a Protected Entity ID if it has a snapshot ID
=> Added GetBaseID function

pkg/pvc/pvc_protected_entity.go, pkg/pvc/pvc_protected_entity_type_manager.go, pkg/pvc/utils.go
When validating the pv provisioner type, we used to restrict it to be vsphere csi, now we can add support for migrated vsphere csi, where the pv spec conforms to in-tree vcp format with "migrated-to" annotation added by vsphere csi
=> Add support for migrated csi volume

.github/workflows/ci.yml, go.mod
Golang 1.16 has a critical vulnerability, therefore upgrading the version to 1.17
=> Upgrade go version to 1.17

MAINTAINERS.md
Signed-off-by: Dave Smith-Uchida <dave@kasten.io>
=> Change Dave Smith-Uchida affiliation to Kasten

Makefile, pkg/localsnap/localsnap_repo.go
Manages snapshot images stored into a local directory.  Useful for Protected Entities that do not have built-in
snapshotting capabilities.
=> Added localsnap repository.

go.mod, go.sum
This change updates gogo protobuf version to 1.3.2.
Precheck in progress.
=> Update gogo protobuf version to 1.3.2
